"""Known constellation metadata templates.

Templates fill empty fields during merge for satellites belonging to known
constellations.  Values are only applied when the record doesn't already
have data from a higher-priority source.
"""

from __future__ import annotations

from typing import Any

CONSTELLATION_TEMPLATES: dict[str, dict[str, Any]] = {
    "starlink": {
        "manufacturer_name": "SpaceX",
        "bus_platform": "Starlink Bus",
        "operator_name": "SpaceX",
        "owner_name": "SpaceX",
        "operator_country_code": "US",
        "operator_country_name": "United States",
        "owner_country_code": "US",
        "owner_country_name": "United States",
        "purpose_primary": "Communications",
        "mission_class": "LEO",
        "civilian_military": "Commercial",
        "design_life_years": 5.0,
    },
    "oneweb": {
        "manufacturer_name": "Airbus Defence and Space",
        "bus_platform": "OneWeb Bus",
        "operator_name": "Eutelsat OneWeb",
        "owner_name": "Eutelsat OneWeb",
        "operator_country_code": "GB",
        "operator_country_name": "United Kingdom",
        "owner_country_code": "GB",
        "owner_country_name": "United Kingdom",
        "purpose_primary": "Communications",
        "mission_class": "LEO",
        "civilian_military": "Commercial",
        "design_life_years": 5.0,
    },
    "iridium": {
        "manufacturer_name": "Motorola",
        "operator_name": "Iridium Communications",
        "owner_name": "Iridium Communications",
        "operator_country_code": "US",
        "operator_country_name": "United States",
        "owner_country_code": "US",
        "owner_country_name": "United States",
        "purpose_primary": "Communications",
        "mission_class": "LEO",
        "civilian_military": "Commercial",
    },
    "iridium next": {
        "manufacturer_name": "Thales Alenia Space",
        "bus_platform": "ELiTeBus-1000",
        "operator_name": "Iridium Communications",
        "owner_name": "Iridium Communications",
        "operator_country_code": "US",
        "operator_country_name": "United States",
        "owner_country_code": "US",
        "owner_country_name": "United States",
        "purpose_primary": "Communications",
        "mission_class": "LEO",
        "civilian_military": "Commercial",
        "design_life_years": 15.0,
    },
    "gps": {
        "manufacturer_name": "Lockheed Martin",
        "operator_name": "United States Space Force",
        "owner_name": "United States Space Force",
        "operator_country_code": "US",
        "operator_country_name": "United States",
        "owner_country_code": "US",
        "owner_country_name": "United States",
        "purpose_primary": "Navigation",
        "mission_class": "MEO",
        "civilian_military": "Military",
        "design_life_years": 12.0,
    },
    "galileo": {
        "manufacturer_name": "OHB System",
        "bus_platform": "SmallGEO",
        "operator_name": "European Union Agency for the Space Programme",
        "owner_name": "European Union",
        "operator_country_code": "ESA",
        "operator_country_name": "ESA",
        "owner_country_code": "ESA",
        "owner_country_name": "ESA",
        "purpose_primary": "Navigation",
        "mission_class": "MEO",
        "civilian_military": "Civil",
        "design_life_years": 12.0,
    },
    "glonass": {
        "manufacturer_name": "ISS Reshetnev",
        "operator_name": "Russian Aerospace Forces",
        "owner_name": "Russian Aerospace Forces",
        "operator_country_code": "RU",
        "operator_country_name": "Russia",
        "owner_country_code": "RU",
        "owner_country_name": "Russia",
        "purpose_primary": "Navigation",
        "mission_class": "MEO",
        "civilian_military": "Military",
        "design_life_years": 7.0,
    },
    "beidou": {
        "manufacturer_name": "CAST",
        "operator_name": "China Satellite Navigation Office",
        "owner_name": "China Satellite Navigation Office",
        "operator_country_code": "CN",
        "operator_country_name": "China",
        "owner_country_code": "CN",
        "owner_country_name": "China",
        "purpose_primary": "Navigation",
        "civilian_military": "Military",
        "design_life_years": 12.0,
    },
    "globalstar": {
        "manufacturer_name": "Thales Alenia Space",
        "operator_name": "Globalstar",
        "owner_name": "Globalstar",
        "operator_country_code": "US",
        "operator_country_name": "United States",
        "owner_country_code": "US",
        "owner_country_name": "United States",
        "purpose_primary": "Communications",
        "mission_class": "LEO",
        "civilian_military": "Commercial",
        "design_life_years": 15.0,
    },
    "orbcomm": {
        "manufacturer_name": "Sierra Nevada Corporation",
        "operator_name": "Orbcomm",
        "owner_name": "Orbcomm",
        "operator_country_code": "US",
        "operator_country_name": "United States",
        "owner_country_code": "US",
        "owner_country_name": "United States",
        "purpose_primary": "Communications",
        "mission_class": "LEO",
        "civilian_military": "Commercial",
    },
    "planet": {
        "manufacturer_name": "Planet Labs",
        "operator_name": "Planet Labs",
        "owner_name": "Planet Labs",
        "operator_country_code": "US",
        "operator_country_name": "United States",
        "owner_country_code": "US",
        "owner_country_name": "United States",
        "purpose_primary": "Earth Observation",
        "mission_class": "LEO",
        "civilian_military": "Commercial",
        "design_life_years": 3.0,
    },
    "spire": {
        "manufacturer_name": "Spire Global",
        "bus_platform": "Lemur-2",
        "operator_name": "Spire Global",
        "owner_name": "Spire Global",
        "operator_country_code": "US",
        "operator_country_name": "United States",
        "owner_country_code": "US",
        "owner_country_name": "United States",
        "purpose_primary": "Earth Observation",
        "mission_class": "LEO",
        "civilian_military": "Commercial",
        "design_life_years": 3.0,
    },
    "intelsat": {
        "operator_name": "Intelsat",
        "owner_name": "Intelsat",
        "operator_country_code": "LU",
        "operator_country_name": "Luxembourg",
        "owner_country_code": "LU",
        "owner_country_name": "Luxembourg",
        "purpose_primary": "Communications",
        "mission_class": "GEO",
        "civilian_military": "Commercial",
    },
    "ses": {
        "operator_name": "SES",
        "owner_name": "SES",
        "operator_country_code": "LU",
        "operator_country_name": "Luxembourg",
        "owner_country_code": "LU",
        "owner_country_name": "Luxembourg",
        "purpose_primary": "Communications",
        "mission_class": "GEO",
        "civilian_military": "Commercial",
    },
    "telesat": {
        "operator_name": "Telesat",
        "owner_name": "Telesat",
        "operator_country_code": "CA",
        "operator_country_name": "Canada",
        "owner_country_code": "CA",
        "owner_country_name": "Canada",
        "purpose_primary": "Communications",
        "civilian_military": "Commercial",
    },
    "cosmo-skymed": {
        "manufacturer_name": "Thales Alenia Space",
        "operator_name": "Italian Space Agency",
        "owner_name": "Italian Space Agency",
        "operator_country_code": "IT",
        "operator_country_name": "Italy",
        "owner_country_code": "IT",
        "owner_country_name": "Italy",
        "purpose_primary": "Earth Observation",
        "civilian_military": "Dual",
        "design_life_years": 5.0,
    },
    "yaogan": {
        "operator_name": "PLA Strategic Support Force",
        "owner_name": "PLA Strategic Support Force",
        "operator_country_code": "CN",
        "operator_country_name": "China",
        "owner_country_code": "CN",
        "owner_country_name": "China",
        "purpose_primary": "Earth Observation",
        "civilian_military": "Military",
    },
}
